medicalstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
    path('customer/', include("customer.urls"))
]

store/urls.py
from django.urls import path
from .views import home_page, register_page, login_page, dashboard_admin, \
    dealers_page, medicines_page, employees_page, customers_page, purchases_page,\
        confirm_logout_page, add_dealer_page, add_medicine_page, add_employee_page,\
            logout_page, add_customer_page, add_purchase_page, settings_page, update_dealer,\
                delete_dealer, update_medicine, delete_medicine, update_employee,\
                    delete_employee, update_customer, delete_customer, update_purchase,\
                        delete_purchase, register_admin, register_customer, \
                            login_admin, login_customer, dashboard_customer

app_name = 'store'

urlpatterns = [
    path('', home_page, name="home"),

    # Register Path
    path('register/', register_page, name="register"),
    path('register/admin/', register_admin, name="register-admin"),
    path('register/customer/', register_customer, name="register-customer"),
    
    # Login Path
    path('login/', login_page, name="login"),
    path('login/admin/', login_admin, name="login-admin"),
    path('login/customer/', login_customer, name="login-customer"),
    
    path('confirm-logout/', confirm_logout_page, name="confirm-logout"),
    path('confirm-logout/logout/', logout_page, name="logout"),
    path('dashboard/admin/', dashboard_admin, name="dashboard-admin"),
    path('dashboard/customer/', dashboard_customer, name="dashboard-customer"),

    # Dealer CRUD
    path('dealers/', dealers_page, name="view-dealers"),
    path('dealers/add-dealer/', add_dealer_page, name="add-dealer"),
    path('dealers/update-dealer/<int:pk>/', update_dealer, name="update-dealer"),
    path('dealers/delete-dealer/<int:pk>/', delete_dealer, name="delete-dealer"),

    # Medicine CRUD
    path('medicines/', medicines_page, name="view-medicines"),
    path('medicines/add-medicine/', add_medicine_page, name="add-medicine"),
    path('medicines/update-medicine/<int:pk>/', update_medicine, name="update-medicine"),
    path('medicines/delete-medicine/<int:pk>/', delete_medicine, name="delete-medicine"),
    
    # Employee CRUD
    path('employees/', employees_page, name="view-employees"),
    path('employees/add-employee/', add_employee_page, name="add-employee"),
    path('employees/update-employee/<int:pk>/', update_employee, name="update-employee"),
    path('employees/delete-employee/<int:pk>/', delete_employee, name="delete-employee"),

    # Customer CRUD
    path('customers/', customers_page, name="view-customers"),
    path('customers/add-customer/', add_customer_page, name="add-customer"),
    path('customers/update-customer/<int:pk>/', update_customer, name="update-customer"),
    path('customers/delete-customer/<int:pk>/', delete_customer, name="delete-customer"),

    # Purchase CRUD
    path('purchases/', purchases_page, name="view-purchases"),
    path('purchases/add-purchase/', add_purchase_page, name="add-purchase"),
    path('purchases/update-purchase/<int:pk>/', update_purchase, name="update-purchase"),
    path('purchases/delete-purchase/<int:pk>/', delete_purchase, name="delete-purchase"),

    path('settings/', settings_page, name="settings")
]

store/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image

class Dealer(models.Model):
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    address = models.TextField()
    phone_number = models.CharField(max_length=15)
    email = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.fname} {self.lname}" 

    def get_update_url(self):
        return reverse("store:update-dealer", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("store:delete-dealer", kwargs={"pk": self.pk})


class Medicine(models.Model):
    med_code = models.IntegerField()
    med_name = models.CharField(max_length=50)
    dealer_name = models.ForeignKey(Dealer, on_delete=models.CASCADE)
    price = models.FloatField()
    stock = models.IntegerField()
    description = models.TextField()

    def __str__(self):
        return f"{self.med_code}: {self.med_name}"

    def get_update_url(self):
        return reverse("store:update-medicine", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("store:delete-medicine", kwargs={"pk": self.pk})


class Employee(models.Model):
    emp_id = models.IntegerField()
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    address = models.TextField()
    salary = models.FloatField()
    phone_number = models.CharField(max_length=15)
    email = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.emp_id}: {self.fname} {self.lname}"

    def get_update_url(self):
        return reverse("store:update-employee", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("store:delete-employee", kwargs={"pk": self.pk})


class Customer(models.Model):
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    address = models.TextField()
    phone_number = models.CharField(max_length=15)
    email = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.fname} {self.lname}"

    def get_update_url(self):
        return reverse("store:update-customer", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("store:delete-customer", kwargs={"pk": self.pk})


class Purchase(models.Model):
    med_name = models.ForeignKey(Medicine, on_delete=models.CASCADE)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    price_number = models.FloatField()
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.med_name} {self.customer}"

    def get_update_url(self):
        return reverse("store:update-purchase", kwargs={"pk": self.pk})

    def get_delete_url(self):
        return reverse("store:delete-purchase", kwargs={"pk": self.pk})


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20)
    profile_picture = models.ImageField(default="users/me.jpg", upload_to="users/")

    def __str__(self):
        return self.user.username

    # Resize User Profile Picture 
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super().save()
        profile_picture = Image.open(self.profile_picture.path)
        if profile_picture.height > 300 or profile_picture.width > 300:
            output_size = (300, 300)
            profile_picture.thumbnail(output_size)
        print(profile_picture)
        

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

store/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, LogUserForm, AddDealerForm,\
    AddMedicineForm, AddEmployeeForm, AddCustomerForm, AddPurchaseForm,\
        UpdateProfileForm, UpdateUserForm, UpdateDealerForm,\
            UpdateMedicineForm, UpdateEmployeeForm, UpdateCustomerForm,\
                UpdatePurchaseForm, AddOrderForm, UpdateOrderForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from store.models import (
    Dealer, Medicine, Employee,
    Customer, Purchase, Profile
)
from customer.models import Order
from django.contrib.auth.forms import UserCreationForm,\
    AuthenticationForm


def home_page(request):
    return render(request, "store/home.html")


def logout_page(request):
    logout(request)
    messages.success(request, "You have successfully logged out!")
    return redirect("store:home")


def login_page(request):
    return render(request, "store/login.html")


def login_admin(request):
    form = LogUserForm()

    if request.method == "POST":
        form = LogUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            print(username, password)
            user = authenticate(
                request, username=username, password=password
            )
            print(user)
            if user is not None:
                login(request, user)
                messages.success(request, f"{username}, you are logged in.")
                return redirect("store:dashboard-admin")
            messages.error(request, f"Oops, the username {username} does not exist in our database. Please try again.")
        return redirect("store:login-admin")

    context = {
        'form': form
    }
    return render(request, "store/login-admin.html", context)


def login_customer(request):
    form = LogUserForm()

    if request.method == "POST":
        form = LogUserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            print(username, password)
            user = authenticate(
                request, username=username, password=password
            )
            print(user)
            if user is not None:
                login(request, user)
                messages.success(request, f"{username}, you are logged in.")
                return redirect("store:dashboard-customer")
            messages.error(request, f"Oops, the username {username} does not exist in our database. Please try again.")
        return redirect("store:login-customer")

    context = {
        'form': form
    }
    return render(request, "store/login-customer.html", context)


def register_page(request):
    return render(request, "store/register.html")


def register_admin(request):
    form = CreateUserForm()
    
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has successfully been created.")
            return redirect("store:login")
        print("Something's not right.")
        return redirect("store:register-admin")

    context = {
        'form': form
    }

    return render(request, "store/register-admin.html", context)


def register_customer(request):
    form = CreateUserForm()
    
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has successfully been created.")
            return redirect("store:login-customer")
        print("Something's not right.")
        return redirect("store:register-customer")

    context = {
        'form': form
    }
    return render(request, "store/register-customer.html", context)


@login_required(login_url="/login/admin/")
def dashboard_admin(request):
    return render(request, "store/dashboard-admin.html")


@login_required(login_url="/login/customer/")
def dashboard_customer(request):
    return render(request, "store/dashboard-customer.html")

"""
Dealers CRUD Starts Here
"""
@login_required(login_url="/login/")
def dealers_page(request):
    dealers = Dealer.objects.all()

    context = {
        'dealers': dealers
    }
    return render(request, "store/view-dealers.html", context)


@login_required(login_url="/login/")
def add_dealer_page(request):
    form = AddDealerForm()

    if request.method == "POST":
        form = AddDealerForm(request.POST)
        if form.is_valid():
            fname = form.cleaned_data.get("fname")
            lname = form.cleaned_data.get("lname")
            address = form.cleaned_data.get("address")
            phone_number = form.cleaned_data.get("phone_number")
            email = form.cleaned_data.get("email")
            print(fname, lname)

            dealer = Dealer(
                fname=fname, lname=lname, address=address,
                phone_number=phone_number, email=email
            )
            dealer.save()
            messages.success(request, "You have added a new dealer.")
            return redirect("store:view-dealers")
        return redirect("store:add-dealer")

    context = {
        'form': form
    }
    return render(request, "store/add-dealer.html", context)


@login_required(login_url="/login/")
def update_dealer(request, pk):
    dealer = Dealer.objects.get(id=pk)
    form = UpdateDealerForm(instance=dealer)

    if request.method == "POST":
        form = UpdateDealerForm(request.POST, instance=dealer)
        if form.is_valid():
            form.save()
            messages.success(request, "You have successfully update that dealer.")
            return redirect("store:view-dealers")
        return redirect("store:update-dealer")

    context = {
        "form": form,
    }
    return render(request, "store/update-dealer.html", context)


@login_required(login_url="/login/")
def delete_dealer(request, pk):
    dealer = Dealer.objects.get(id=pk)
    dealer.delete()
    messages.success(request, "You have successfully deleted that dealer.")
    return redirect("store:view-dealers")

"""
Dealers CRUD Ends Here
"""

"""
Medicine CRUD Starts Here
"""
@login_required(login_url="/login/")
def medicines_page(request):
    medicines = Medicine.objects.all()

    context = {
        "medicines": medicines
    }
    return render(request, "store/view-medicines.html", context)


@login_required(login_url="/login/")
def add_medicine_page(request):
    form = AddMedicineForm()

    if request.method == "POST":
        form = AddMedicineForm(request.POST)
        if form.is_valid():
            med_code = form.cleaned_data.get("med_code")
            med_name = form.cleaned_data.get("med_name")
            dealer_name = form.cleaned_data.get("dealer_name")
            price = form.cleaned_data.get("price")
            stock = form.cleaned_data.get("stock")
            description = form.cleaned_data.get("description")

            medicine = Medicine(
                med_code=med_code, med_name=med_name, dealer_name=dealer_name,
                price=price, stock=stock, description=description
            )
            medicine.save()
            messages.success(request, "You have added a new medicine.")
            return redirect("store:view-medicines")
        return redirect("store:add-medicine")

    context = {
        "form": form
    }
    return render(request, "store/add-medicine.html", context)


@login_required(login_url="/login/")
def update_medicine(request, pk):
    medicine = Medicine.objects.get(id=pk)
    form = UpdateMedicineForm(instance=medicine)

    if request.method == "POST":
        form = UpdateMedicineForm(request.POST, instance=medicine)
        if form.is_valid():
            form.save()
            messages.success(request, "You have successfully update that medicine.")
            return redirect("store:view-medicines")
        return redirect("store:update-medicine")

    context = {
        "form": form,
    }
    return render(request, "store/update-medicine.html", context)


@login_required(login_url="/login/")
def delete_medicine(request, pk):
    medicine = Medicine.objects.get(id=pk)
    medicine.delete()
    messages.success(request, "You have successfully deleted that medicine.")
    return redirect("store:view-medicines")

"""
Medicine CRUD Ends Here
"""

"""
Employees CRUD Starts Here
"""
@login_required(login_url="/login/")
def employees_page(request):
    employees = Employee.objects.all()

    context = {
        "employees": employees
    }
    return render(request, "store/view-employees.html", context)


@login_required(login_url="/login/")
def add_employee_page(request):
    form = AddEmployeeForm()

    if request.method == "POST":
        form = AddEmployeeForm(request.POST)
        if form.is_valid():
            """
            imports random function to randomly create a unique emp_id
            """
            import random

            emp_id = random.randrange(000, 999)
            fname = form.cleaned_data.get("fname")
            lname = form.cleaned_data.get("lname")
            address = form.cleaned_data.get("address")
            salary = form.cleaned_data.get("salary")
            phone_number = form.cleaned_data.get("phone_number")
            email = form.cleaned_data.get("email")

            employee = Employee(
                emp_id=emp_id, fname=fname, lname=lname, address=address,

store/templates/store/_header.html
{% load static %}
<header class="home__header">
    <!-- <nav class="navbar-expand-sm top__nav">
        <div class="container">
            <div class="top__nav__flex">
                <div class="tel">
                    <i class="fa fa-mobile" aria-hidden="true"></i>
                    <p class="tel__num">
                        +2348137281916
                    </p>
                </div>

                <ul class="socials navbar-nav">
                    <li class="social nav-item">
                        <a href="" class="nav-link">
                           <i class="fa fa-facebook-official" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="social nav-item">
                        <a href="" class="nav-link">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="social nav-item">
                        <a href="" class="nav-link">
                            <i class="fa fa-github" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav> -->

    <nav class="navbar-expand-sm main__nav">
        <div class="container-fluid">
            <div class="main__nav__body">
                <div class="main__nav__flex">
                    <!-- Logo -->
                    <a href="{% url "store:home" %}" class="navbar-brand">
                        <img src="https://tse1.mm.bing.net/th?id=OIP.Zj_n3e57ssjLhwmw06Xs0AHaHa&pid=Api&P=0&h=180" alt="" class="img-responsive">
                        <span class="logo__name">
                            Affordable Medical Store
                        </span>
                    </a>
                    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
                        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
    
                        <!-- Main Login/Register -->
                        <ul class="accounts navbar-nav">
                            
                            {% if user.is_authenticated %}
                            <li class="accounts navbar-nav">
                                <a href="{% url 'store:logout' %}" class="nav-link">
                                    Logout 
                                </a>
                            </li>
                            {% else %}
                            <a href="{% url 'store:register' %}" class="nav-link">
                                Register 
                            </a>
                            {% endif %}
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </nav>

</header>

store/templates/store/add-customer.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
    <section id="dashboard_section" class="dashboard_section">

        <!-- Dashboard Sidebar -->
        {% include "store/_dashboard-admin.html" %}

        <div class="container-fluid">
            <div class="add_dealer">
                <div class="customer__card card">
                    <p class="h2">
                        Add Customer
                    </p>

                    <div class="add__dealer__form">
                        <div class="container">
                            <form class="row g-3 needs-validation" method="POST">
                            {% csrf_token %}

                                <div class="col-md-6">
                                    <label for="validationCustomFirstName" class="form-label">
                                        First Name:
                                    </label>
                                    <div class="input-group">
                                       
                                        {{ form.fname }}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label for="validationCustomLastName" class="form-label">
                                        Last Name:
                                    </label>
                                    <div class="input-group">
                                       
                                        {{ form.lname }}
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <label for="validationPhoneNumber" class="form-label">
                                        Phone Number:
                                    </label>

                                    <div class="input-group">
                                       
                                        {{ form.phone_number }}
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <label for="validationEmail" class="form-label">
                                        Email:
                                    </label>

                                    <div class="input-group">
                                       
                                        {{ form.email }}
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="validationAddress" class="form-label">
                                            Address:
                                        </label>
                                        {{ form.address }}
                                    </div>
                                </div>

                                <div class="col-12 pt-3">
                                    <div class="col-12 pb-3">
                                        <button class="btn btn-block login-button" type="submit">
                                            Submit
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/6e47be172b.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="shortcut icon" href="https://tse1.mm.bing.net/th?id=OIP.Zj_n3e57ssjLhwmw06Xs0AHaHa&pid=Api&P=0&h=180" type="image/x-icon">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    {% block content %}{% endblock content %}

    <script src="{% static 'js/mdb.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

store/templates/store/confirm-logout.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
    <section id="dashboard_section" class="dashboard_section">

        <!-- Dashboard Sidebar -->
        {% include "store/_dashboard-admin.html" %}

        <div class="container-fluid">
            <div class="confirm__logout m-auto">
                <div class="card confirm__card">
                    <p class="h2">
                        Are you sure you want to logout?
                    </p>

                    <div class="confirm">
                        <a href="{% url 'store:logout' %}" class="btn bg-danger">
                            Yes!
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

store/templates/store/dashboard-customer.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}
  <style>
    div.dashboard{
      margin-top: 50px;
    }

    div.dash_card{
      border-radius: 20px;
      margin-bottom: 50px;
    }

    div.dash_card:last-child{
      margin-bottom: 100px;
    }

    div.head{
      padding: 20px;
    }

    p.h3{
      color: #3b3ef6;
      font-weight: 600;
      margin-left: 10px;
    }

    div.head svg{
      font-size: 28px;
      color: #3b3ef6;
    }

    div.messages{
      margin: auto;
      width: 100%;
    }

    p.alert {
      font-weight: 600;
    }

    @media screen and (max-width: 785px){
        div.messages{
          width: 80% !important;
        }
    }
  </style>

  <section id="dashboard_section" class="dashboard_section">
        
        <!-- Dashboard Sidebar -->
        {% include "store/_dashboard-customer.html" %}

        <div class="container-fluid">
            <div class="dashboard">

              {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                    <p{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                        {{ message }}
                    </p>
                    {% endfor %}
                </div>
              {% endif %}

              <div class="row">
                  <div class="col-md-6">
                  <div class="card dash_card">
                    <div class="head d-flex">
                      

                      <p class="pl-5 h3">
                        Medicines
                      </p>
                    </div>
                    <div class="footer card-footer d-flex justify-content-between bg-black">
                      <a href="{% url "store:view-medicines" %}" class="nav-link pr-5">
                        View

                       
                      </a>
                    </div>
                  </div>
                </div>
                
                <div class="col-md-6">
                  <div class="card dash_card">
                    <div class="head d-flex">
                      

                      <p class="pl-5 h3">
                        Orders
                      </p>
                    </div>
                    <div class="footer card-footer d-flex justify-content-between bg-black">
                      <a href="{% url "store:view-dealers" %}" class="nav-link pr-5">
                        View

                        
                      </a>
                    </div>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="card dash_card">
                    <div class="head d-flex">
                     
                      <p class="pl-5 h3">
                        Purchases
                      </p>
                    </div>
                    <div class="footer card-footer d-flex justify-content-between bg-black">
                      <a href="{% url "store:view-purchases" %}" class="nav-link pr-5">
                        View

                       
                      </a>
                    </div>
                  </div>
                </div>

                <div class="col-md-6">
                  <div class="card dash_card">
                    <div class="head d-flex">
                     

                      <p class="pl-5 h3">
                        Profile
                      </p>
                    </div>
                    <div class="footer card-footer d-flex justify-content-between bg-black">
                      <a href="{% url "store:settings" %}" class="nav-link pr-5">
                        View

                       
                      </a>
                    </div>
                  </div>
                </div>

              </div>
            </div>
        </div>
  </section>
{% endblock content %}